### ISSUE TITLE
How to calculate MAP?

### ISSUE THREAD

**Issue by LeviChenhh** [qliu24/SAKE#1]
Thank you for your paper and code. When I run your code, I find the evaluation index acc@1, acc@5. So, where the code to calculate MAP?
Looking forward to your reply

**Comment by LeviChenhh** [comment]
forget to mention：when train

**Comment by qliu24** [comment]
Hi,

I didn’t include the code to monitor mAP during training, but you can find it in the test script.

Qing

On Apr 15, 2020, at 9:58 PM, LeviChenhh <notifications@github.com<mailto:notifications@github.com>> wrote:



forget to mention：when train
