### ISSUE TITLE
Would you like to tell me  how to visualize top-K retrieval results，thank

### ISSUE THREAD

**Issue by Qingzhang1994** [qliu24/SAKE#10]
![image](https://user-images.githubusercontent.com/48178899/191701328-1db7ca37-b1fe-41dd-a705-b0ac6f0e4ebb.png)

**Comment by qliu24** [comment]
By comparing the embedding of the query image (sketch) vs the real images in the candidate pool, you can rank the real images and find the top K retrieval results. Then I used python matplotlib package to get the plot.

**Comment by Qingzhang1994** [comment]
Thank you for your reply。 I have some questions, how to build the Sketchy Ext. ([16] Split) experiment
![image](https://user-images.githubusercontent.com/48178899/195967762-fc167f6b-c021-4c57-8c4f-c4022a897c21.png)
![image](https://user-images.githubusercontent.com/48178899/195967784-5a0f7b7a-d4b5-4a14-9ac0-5f36d17d371b.png)

**Comment by qliu24** [comment]
You can find the train/val split from the reference paper.
