### ISSUE TITLE
How to compose a training batch?

### ISSUE THREAD

**Issue by bebory** [qliu24/SAKE#2]
I note that when training, you use some sketch images and some real images to make a batch. 

Can you tell me how many sketch images and how many real images this batch contains?

Thanks!

**Comment by qliu24** [comment]
In TU-Berlin, sketch image number = batch_size//10, photo image number = batch_size//10 * 9.
In Sketchy, sketch image number = batch_size//3, photo image number = batch_size//3 * 2.
