### ISSUE TITLE
Sketchy zeroshot2 missing

### ISSUE THREAD

**Issue by clickmouse** [qliu24/SAKE#4]
Hello, I want to know how to follow your work of Sketchy zeroshot2. There is no directory of this split.

**Comment by qliu24** [comment]
The second Sketchy Ext. split was introduced in the paper "[16] Sasi Kiran Yelamarthi, Shiva Krishna Reddy, Ashish Mishra, and Anurag Mittal. A zero-shot framework for sketch based image retrieval. In Proceedings of the European Conference on Computer Vision, pages 300–317, 2018". You can find their data file link in "https://github.com/ShivaKrishnaM/ZS-SBIR". The zero-shot classes are stored in the "test_split_ref.npy" file.

**Comment by Qingzhang1994** [comment]
> Hello, I want to know how to follow your work of Sketchy zeroshot2. There is no directory of this split.

请问这个问题您解决了吗。我也想做一下这个实验，不知道该怎么做。
![image](https://user-images.githubusercontent.com/48178899/195967693-14a0c308-1877-4791-87a5-b33a7caa62d4.png)
