### ISSUE TITLE
tag_all

### ISSUE THREAD

**Issue by Mdahao** [qliu24/SAKE#7]
https://github.com/qliu24/SAKE/blob/bdae8d6f04e648fe94b7e4b0f6ae4e09abcfcbc0/src/train_cse_resnet_tuberlin_ext.py#L221

Hi，thanks for your work. And  I have a question that what the tag_all is.

**Comment by qliu24** [comment]
Hi, `tag_all` indicates whether the input is a sketch or a photo image. It is used in the conditional model (CSE-ResNet) as a domain indicator.
