### ISSUE TITLE
KD loss

### ISSUE THREAD

**Issue by Mdahao** [qliu24/SAKE#8]
https://github.com/qliu24/SAKE/blob/aad0fe3236c63fff7875ad0ad6e8ba2e59a05fef/src/train_cse_resnet_tuberlin_ext.py#L247

Hi ，thanks for your work.  Have you tried to use KL difference to calculate loss？

**Comment by develop-productivity** [comment]
> https://github.com/qliu24/SAKE/blob/aad0fe3236c63fff7875ad0ad6e8ba2e59a05fef/src/train_cse_resnet_tuberlin_ext.py#L247
> 
> Hi ，thanks for your work. Have you tried to use KL difference to calculate loss？

Hello here, I meet the error of `NameError: name 'pretrainedmodels' is not defined`.
Do you know where to find the pretrainedmodels.py file.
One more thing, I download the pretrained model but the 'model_best.pth.tar' has breoken, do you know how to solve this problem？
Thank you !

**Comment by qliu24** [comment]
@Mdahao  No, we didn't try use KL loss in our experiments, but it should be very similar to the cross-entropy loss.

@develop-productivity  You can find `pretrainedmodels` from https://github.com/Cadene/pretrained-models.pytorch .
Regarding the `model_best.pth.tar`, I just tried download and `torch.load` in my machine, both work fine.
